### ISSUE TITLE
Issue for missing recapture date and time for Technosmarts and Igotu/cattrack

### ISSUE THREAD

**Issue by francisvolh** [allisonglider/seabiRds#59]
when reading data from GPS devices seabiRds does not require recapture dates. This is troublesome if there is an error in the inputing the data in the deployment file. Only Ecotone devices (for the Arctic Elliot Lab) should be allowed without restrictions if there is no recapture date. Technosmarts and Igotu/cattracks should have a warning or error message if there is no recapture time to avoid issues.

**Comment by allisonglider** [comment]
Hi Francis, I have added in the warning you requested for all loggers that require device retrieval to get data (e.g. Technomsart, Igotu, and Lotek TDRs). Could you test it using the dev branch?

devtools::install_github("allisonglider/seabiRds@dev")

**Comment by francisvolh** [comment]
tested and works great!
